---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  ##
  # Create service selector labels here
  ##
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  ##
  # create non-sensitive data attributes
  ##
  database: wordpress
  user: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ##
  # Create app label selectors here
  ##
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    ##
    # Create metadata labels here
    ##
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wordpress-mysql
                  key: database
